# logging
logging:
  config: classpath:log4j2/log4j2-spring.xml
server:
  port: 10030
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /svcenter
spring:
  datasource:
    url: jdbc:mysql://120.77.253.177:3306/monitortool?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=true
    username: root
    password: mima1234
    driverClassName: com.mysql.jdbc.Driver
    filters : stat,log4j2
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 10
    initialSize: 2
    maxWait: 60000
    maxIdle: 5
    minIdle: 2
    defaultAutoCommit: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow : false
    testOnReturn : false
    poolPreparedStatements : true
    maxOpenPreparedStatements : 20
    # druid 监控日志输出间隔
    timeBetweenLogStatsMillis: 60000
  jackson: #jackson
    default-property-inclusion: non_null
    jackson.date-format: yyyy/MM/dd HH:mm:ss
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.croakzh.webfront.po,com.quickwork.webfront.vo
  mapper-locations: classpath:com/croakzh/webfront/mapper/*Mapper.xml
